version: '3.8'

services:
  web:
    build: .
    container_name: nextjs_web
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/nextjsdb
    volumes:
      - ./app:/app

  mongo:
    image: mongo:6
    container_name: mongo_db
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
