version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MONGODB_URI: mongodb+srv://xxxua:pluH6e7jXGPxE0lB@userdata.9jlqo6m.mongodb.net/?retryWrites=true&w=majority&appName=UserData
        JWT_SECRET: 3f66f61e8210bfd24cb74353c2228408e5d3d996a0de3f6e02604675608ddc9
    container_name: gamervault-part2
    ports:
      - '3100:3000'
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb+srv://xxxua:pluH6e7jXGPxE0lB@userdata.9jlqo6m.mongodb.net/?retryWrites=true&w=majority&appName=UserData
      - JWT_SECRET=3f66f61e8210bfd24cb74353c2228408e5d3d996a0de3f6e02604675608ddc9

  mongo:
    image: mongo:8
    container_name: mongo_db-part2
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: