version: '3.8'

services:
  web:
    build: 
      context: .
      args:
        MONGODB_URI: mongodb://mongo:28017/nextjsdb
        JWT_SECRET: 3f66f61e8210bfd24cb74353c2228408e5d3d996a0de3f6e02604675608ddc9
    container_name: gamervault-part2
    ports:
      - '3100:3000'
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:28017/nextjsdb
      - JWT_SECRET=3f66f61e8210bfd24cb74353c2228408e5d3d996a0de3f6e02604675608ddc9
    # volumes:
    #   - ./gamervault-src:/gamervault-src
    #   - /gamervault-src/node_modules



  mongo:
    image: mongo:6
    container_name: mongo_db-part2
    ports:
      - '28017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: