version: '3.8'

services:
  web:
    build: .
    container_name: gamervault-part2
    ports:
      - '3100:3000'
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/nextjsdb
      - JWT_SECRET=3f66f61e8210bfd24cb74353c2228408e5d3d996a0de3f6e02604675608ddc9
    volumes:
      - ./gamervault-src:/gamervault-src

  mongo:
    image: mongo:6
    container_name: mongo_db-part2
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: